name-template: 'v$RESOLVED_VERSION 💡'
tag-template: 'v$RESOLVED_VERSION'
categories:
    -   title: '🌟 Features'
        collapse-after: 20
        labels:
            - 'feature'
            - 'enhancement'
    -   title: '🐞 Bug Fixes'
        collapse-after: 10
        labels:
            - 'fix'
            - 'bugfix'
            - 'bug'
    -   title: '🔧 Maintenance'
        collapse-after: 5
        label: 'chore'
    -   title: '⬆️ Dependencies'
        collapse-after: 5
        label: 'dependencies'
    -   title: '📃 Documentation'
        collapse-after: 5
        label: 'documentation'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
    major:
        labels:
            - 'major'
    minor:
        labels:
            - 'minor'
    patch:
        labels:
            - 'patch'
    default: patch
exclude-labels:
    - 'skip-changelog'
autolabeler:
    -   label: 'enhancement'
        title:
            - '/^feat/i'
    -   label: 'bug'
        title:
            - '/^fix/i'
    -   label: 'chore'
        title:
            - '/^chore/i'
    -   label: 'documentation'
        title:
            - '/^docs/i'
    -   label: 'dependencies'
        title:
            - '/^dependencies/i'
template: |
    ## Changes

    $CHANGES
header: |
    [Panelop Project](https://github.com/users/marsskom/projects/2)
footer: |
    Thanks to: $CONTRIBUTORS
