name: Greetings

on: [pull_request, issues]

jobs:
    greeting:
        runs-on: ubuntu-latest
        permissions:
            issues: write
            pull-requests: write
        steps:
            - uses: actions/first-interaction@v1
              with:
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  issue-message: 'Hi! Thanks a lot for an issue! Please, check if the issue is created by template.'
                  pr-message: 'Hi! It is incredible first pull request from you! Please, check if the PR is created by
          template.'
