name: "PHP CS"

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    phpcs:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0 # important!

            - name: Setup PHP environment
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.1
                  extensions: none, ctype, curl, date, dom, json, libxml, mbstring, pdo_mysql, phar, simplexml, soap, tokenizer, xml, xmlwriter, zlib, bcmath, intl
                  coverage: none
                  tools: phpcs

            - name: Run PHPCS
              run: phpcs phpcs.xml
