name: "PHP STAN"

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    phpstan:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: php-actions/composer@v6 # or alternative dependency management
            - uses: php-actions/phpstan@v3
              with:
                  version: 1.9.18
                  php_version: 8.1
                  path: src
