name: "Psalm Static analysis"

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    psalm:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup PHP environment
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.1.14
                  extensions: none, ctype, curl, date, dom, json, libxml, mbstring, pdo_mysql, phar, simplexml, soap, tokenizer, xml, xmlwriter, zlib, bcmath, intl
                  coverage: none
                  tools: vimeo/psalm

            - name: Cache Composer packages
              id: composer-cache
              uses: actions/cache@v2
              with:
                  path: vendor
                  key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-php-
            - name: Install dependencies
              run: composer install --prefer-dist --no-progress --no-interaction

            - name: Run Psalm
              run: psalm src/
